//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int BitConsecutivo { get; set; }
        public System.DateTime BitFecha { get; set; }
        public string BitUsuario { get; set; }
        public string BitAccion { get; set; }
        public string BitAccionBackup { get; set; }
        public string BitNotas { get; set; }
    }
}
