//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string ClieNumInt { get; set; }
        public string ClieNumExt { get; set; }
        public string CIUDAD { get; set; }
        public string EstID { get; set; }
        public string PaisID { get; set; }
        public string CliCodPost { get; set; }
        public string CliRFC { get; set; }
        public Nullable<int> CliSSN { get; set; }
        public string CliIRS { get; set; }
        public string TELEFONO { get; set; }
        public string Telefono2 { get; set; }
        public string URL { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> CliDesde { get; set; }
        public Nullable<float> CliManejosEx { get; set; }
        public Nullable<float> CliServCompEx { get; set; }
        public Nullable<float> CliServCompIm { get; set; }
        public Nullable<float> CliHandlingIm { get; set; }
        public Nullable<int> CliAcumTransAñoP { get; set; }
        public Nullable<int> CliAcumTransAñoD { get; set; }
        public Nullable<decimal> CliAcumPesos { get; set; }
        public Nullable<decimal> CliAcumDolar { get; set; }
        public Nullable<decimal> CliPagaPesos { get; set; }
        public Nullable<decimal> CliPagaDolar { get; set; }
        public Nullable<int> CliTotTrans { get; set; }
        public Nullable<float> TabID { get; set; }
        public Nullable<float> TabIDImp { get; set; }
        public Nullable<float> TabIDCtaAm { get; set; }
        public string TipPtoID { get; set; }
        public string TipPtoID1 { get; set; }
        public Nullable<bool> CliRelAABCli { get; set; }
        public Nullable<bool> CliRelAABPro { get; set; }
        public Nullable<bool> CliRelAABPag { get; set; }
        public Nullable<bool> CliRelAABDes { get; set; }
        public string CliFactA { get; set; }
        public Nullable<short> CliViaMensajes { get; set; }
        public Nullable<float> CliFacDescuento { get; set; }
        public Nullable<bool> CliManejosEsp { get; set; }
        public Nullable<float> CliFactHonorarios { get; set; }
        public Nullable<float> CliFactHonorariosImp { get; set; }
        public string RegOrigId { get; set; }
        public string MetValID { get; set; }
        public Nullable<bool> CliPITEX { get; set; }
        public Nullable<bool> CliMaquiladora { get; set; }
        public string CliPasswordInternet { get; set; }
        public Nullable<bool> CliEnvaMatriz { get; set; }
        public Nullable<bool> CliRegla8a { get; set; }
        public string CliFraccionR8a { get; set; }
        public string CliColonia { get; set; }
        public string CliEsquina { get; set; }
        public Nullable<int> CliSector { get; set; }
        public string ImpAraID { get; set; }
        public string IDProSec { get; set; }
        public string NumClienteTFM { get; set; }
        public Nullable<bool> ActaConstitutiva { get; set; }
        public Nullable<bool> CIF { get; set; }
        public string CURP { get; set; }
        public Nullable<bool> R1_SHCP { get; set; }
        public string AgrupCliCtaMex { get; set; }
        public string AgrupCliCtaAm { get; set; }
        public string AgrupCliFede { get; set; }
        public string AltaPor { get; set; }
        public Nullable<System.DateTime> FHAltaPor { get; set; }
        public string CliObs { get; set; }
        public string Actualizo { get; set; }
        public Nullable<System.DateTime> FHActualizo { get; set; }
        public string NombreCorto { get; set; }
        public Nullable<bool> ActivarPS { get; set; }
        public Nullable<bool> ActivarR8va { get; set; }
        public Nullable<bool> CliActivo { get; set; }
    }
}
