//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public string EstID { get; set; }
        public string EstNombre { get; set; }
        public string EstPais { get; set; }
        public string EstSiglaSaaim3 { get; set; }
        public string PaisID { get; set; }
    }
}
