//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public string PaisID { get; set; }
        public string PaisIDSAIIM3 { get; set; }
        public string PaisNombre { get; set; }
        public string PaisNombreSAIIM3 { get; set; }
        public Nullable<bool> PaisTratadoconMex { get; set; }
        public string PaisNombreTratado { get; set; }
        public string PaisAbrev { get; set; }
        public Nullable<bool> PaisAviso { get; set; }
        public Nullable<bool> PaisparaEtiq { get; set; }
        public string Pais6 { get; set; }
    }
}
