//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuID { get; set; }
        public string UsuNombre { get; set; }
        public string UsuUsuario { get; set; }
        public string UsuContrasena { get; set; }
        public string UsuTipo { get; set; }
        public string UsuCorreo { get; set; }
        public bool UsuActivo { get; set; }
    }
}
